ALTER TABLE tasks ADD COLUMN lines_added INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN lines_removed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN commit_count INTEGER NOT NULL DEFAULT 0;
