use std::collections::HashMap;
use std::fmt;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use crate::context::ToolCtx;
use crate::protocol::{
    CallToolResult, ContentBlock, Implementation, InitializeResult, ListToolsResult,
    ServerCapabilities, ToolInfo, ToolsCapability,
};
use crate::transport::{StdioTransport, TransportError};

/// A tool's result: either success text or error text.
pub type ToolResult = CallToolResult;

/// Error type returned by tool handlers.
///
/// Wraps a string message. In the MCP response, this becomes a
/// `CallToolResult` with `is_error: true`.
pub struct ToolError(pub String);

impl ToolError {
    pub fn new(msg: impl Into<String>) -> Self {
        Self(msg.into())
    }
}

impl fmt::Debug for ToolError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&self.0, f)
    }
}

impl fmt::Display for ToolError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for ToolError {}

impl From<String> for ToolError {
    fn from(s: String) -> Self {
        Self(s)
    }
}

impl From<&str> for ToolError {
    fn from(s: &str) -> Self {
        Self(s.to_owned())
    }
}

/// The core trait for tools. Implemented by the `tool!` macro.
pub trait Tool: 'static {
    type Args: for<'a> facet::Facet<'a>;
    type Result: for<'a> facet::Facet<'a>;

    fn name() -> &'static str;
    fn description() -> &'static str;
    fn call(
        args: Self::Args,
        ctx: &ToolCtx,
    ) -> impl Future<Output = Result<Self::Result, ToolError>> + Send;
}

/// Type-erased dispatch function.
type DispatchFn = Arc<
    dyn for<'a> Fn(
            &'a facet_json::RawJson<'static>,
            &'a ToolCtx,
        ) -> Pin<Box<dyn Future<Output = CallToolResult> + Send + 'a>>
        + Send
        + Sync,
>;

#[derive(Debug)]
pub enum ServerError {
    Transport(TransportError),
    SerializeFailed(String),
}

impl fmt::Display for ServerError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Transport(e) => write!(f, "{e}"),
            Self::SerializeFailed(msg) => write!(f, "failed to serialize MCP result: {msg}"),
        }
    }
}

impl std::error::Error for ServerError {}

impl From<TransportError> for ServerError {
    fn from(e: TransportError) -> Self {
        Self::Transport(e)
    }
}

pub struct McpServerInfo {
    pub name: String,
    pub version: String,
}

/// An MCP server that reads JSON-RPC from stdin and writes to stdout.
pub struct McpServer {
    tools: Vec<ToolInfo>,
    dispatchers: HashMap<String, DispatchFn>,
    ctx: ToolCtx,
    info: McpServerInfo,
}

impl McpServer {
    pub fn new(ctx: ToolCtx, info: McpServerInfo) -> Self {
        Self {
            tools: Vec::new(),
            dispatchers: HashMap::new(),
            ctx,
            info,
        }
    }

    /// Register a tool. The tool's schemas, name, and description are derived
    /// from the `Tool` trait impl (generated by the `tool!` macro).
    pub fn tool<T: Tool>(mut self) -> Self {
        let name = T::name();
        let description = T::description().trim().to_owned();

        let desc = description;
        let info = ToolInfo {
            name: name.to_owned(),
            title: None,
            description: if desc.is_empty() { None } else { Some(desc) },
            input_schema: facet_json_schema::schema_for::<T::Args>(),
            output_schema: Some(facet_json_schema::schema_for::<T::Result>()),
            annotations: None,
            execution: None,
            icons: None,
            _meta: None,
        };
        self.tools.push(info);

        let dispatch: DispatchFn = Arc::new(|raw, ctx| {
            Box::pin(async move {
                let args: T::Args = match facet_json::from_str(raw.as_ref()) {
                    Ok(a) => a,
                    Err(e) => {
                        return CallToolResult::error(format!(
                            "invalid arguments for {}: {e}",
                            T::name()
                        ))
                    }
                };
                match T::call(args, ctx).await {
                    Ok(result) => match facet_json::to_string(&result) {
                        Ok(json) => CallToolResult {
                            content: vec![ContentBlock::Text {
                                text: json.clone(),
                                annotations: None,
                            }],
                            structured_content: Some(facet_json::RawJson::from_owned(json)),
                            is_error: None,
                            _meta: None,
                        },
                        Err(e) => CallToolResult::error(format!(
                            "failed to serialize result for {}: {e}",
                            T::name()
                        )),
                    },
                    Err(e) => CallToolResult::error(e.to_string()),
                }
            })
        });
        self.dispatchers.insert(name.to_owned(), dispatch);

        self
    }

    fn serialize<T: for<'a> facet::Facet<'a>>(&self, value: &T) -> Result<String, ServerError> {
        facet_json::to_string(value).map_err(|e| ServerError::SerializeFailed(e.to_string()))
    }

    pub async fn run(self) -> Result<(), ServerError> {
        let mut transport = StdioTransport::new();

        loop {
            let Some(request) = transport.read_request().await? else {
                break;
            };

            tracing::debug!(method = %request.method, "handling request");

            let response_result = match request.method.as_str() {
                "initialize" => {
                    let result = InitializeResult {
                        protocol_version: "2025-11-25".to_owned(),
                        capabilities: ServerCapabilities {
                            tools: Some(ToolsCapability {
                                list_changed: Some(false),
                            }),
                            experimental: None,
                            logging: None,
                            completions: None,
                            prompts: None,
                            resources: None,
                            tasks: None,
                        },
                        server_info: Implementation {
                            name: self.info.name.clone(),
                            title: None,
                            version: self.info.version.clone(),
                            description: None,
                            website_url: None,
                            icons: None,
                        },
                        instructions: None,
                        _meta: None,
                    };
                    Some(self.serialize(&result)?)
                }
                "notifications/initialized" => None,
                "tools/list" => {
                    let result = ListToolsResult {
                        tools: self.tools.clone(),
                        next_cursor: None,
                        _meta: None,
                    };
                    Some(self.serialize(&result)?)
                }
                "tools/call" => {
                    let result = match &request.params {
                        Some(p) => {
                            match facet_json::from_str::<crate::protocol::CallToolParams>(
                                p.as_ref(),
                            ) {
                                Ok(params) => {
                                    let empty =
                                        facet_json::RawJson::from_owned("{}".to_owned());
                                    let raw = params.arguments.as_ref().unwrap_or(&empty);
                                    match self.dispatchers.get(&params.name) {
                                        Some(dispatch) => dispatch(raw, &self.ctx).await,
                                        None => CallToolResult::error(format!(
                                            "unknown tool: {}",
                                            params.name
                                        )),
                                    }
                                }
                                Err(e) => CallToolResult::error(format!(
                                    "invalid tools/call params: {e}"
                                )),
                            }
                        }
                        None => CallToolResult::error("tools/call requires params"),
                    };
                    Some(self.serialize(&result)?)
                }
                other => {
                    tracing::warn!(method = %other, "unknown MCP method");
                    None
                }
            };

            if let (Some(id), Some(result)) = (request.id, response_result) {
                transport.write_response(id, result).await?;
            }
        }

        Ok(())
    }
}
